version: '3.8'

services:
    app:
      build: .
      ports:
        - "8085:80"
      networks:
        - app-network

    mysql:
      image: mysql:8.0
      restart: unless-stopped
      environment:
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
      networks:
        - app-network
      volumes:
        - data-volume:/var/lib/mysql

    redis:
      image: redis:6.2
      restart: unless-stopped
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
