version: '3'

services:
    app:
      build: .
      ports:
        - "8085:80"
      volumes:
        - ./:/usr/share/nginx
      networks:
        - app-network

    mysql:
      image: mysql:8.0
      restart: unless-stopped
      environment:
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
